// generated by jsonenums -type=State; DO NOT EDIT

package job

import (
	"encoding/json"
	"fmt"
)

var (
	_StateNameToValue = map[string]State{
		"Succeeded": Succeeded,
		"Failed":    Failed,
		"Running":   Running,
	}

	_StateValueToName = map[State]string{
		Succeeded: "Succeeded",
		Failed:    "Failed",
		Running:   "Running",
	}
)

func init() {
	var v State
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_StateNameToValue = map[string]State{
			interface{}(Succeeded).(fmt.Stringer).String(): Succeeded,
			interface{}(Failed).(fmt.Stringer).String():    Failed,
			interface{}(Running).(fmt.Stringer).String():   Running,
		}
	}
}

// MarshalJSON is generated so State satisfies json.Marshaler.
func (r State) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _StateValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid State: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so State satisfies json.Unmarshaler.
func (r *State) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("State should be a string, got %s", data)
	}
	v, ok := _StateNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid State %q", s)
	}
	*r = v
	return nil
}
